#!/usr/bin/env bash
ARCHIVE="https://odooku.s3.amazonaws.com/libraries/vendor/lessc.tar.gz"

if [ ! -f ".heroku/vendor/bin/lessc" ]; then
  puts-step "Bootstrapping lessc"
  mkdir -p .heroku/vendor
  curl -s $ARCHIVE 2> /dev/null | tar zxv -C .heroku/vendor &> /dev/null
fi
