#!/usr/bin/env bash

GITHUB_API_URL="https://api.github.com"
GITHUB_URL="https://github.com"

ODOO_REPO=`$JQ -r .odoo.repo ./odooku.json`
ODOO_BRANCH=`$JQ -r .odoo.branch ./odooku.json`
ODOO_COMMIT=`$JQ -r .odoo.commit ./odooku.json`

if [ $ODOO_COMMIT == "null" ]; then
  # Grab latest commit from github api
  ODOO_COMMIT=`curl -s $GITHUB_API_URL/repos/$ODOO_REPO/commits/$ODOO_BRANCH  2> /dev/null | $JQ -r '.sha'`
  puts-line "Using latest commit $ODOO_REPO (${ODOO_BRANCH}) @ (${ODOO_COMMIT})"
fi

# Create final stack
STACK="{\"odoo\":{\"repo\": \"$ODOO_REPO\", \"branch\": \"$ODOO_BRANCH\", \"commit\": \"$ODOO_COMMIT\"}}"

# See if anything has changed
if [ ! -f ".heroku/odoo/stack.json" ] || [ `echo $STACK | $JQ -cS .` != `$JQ -cS . .heroku/odoo/stack.json` ]; then

  puts-line "New Odoo installation detected"
  ODOO_ARCHIVE="$GITHUB_URL/$ODOO_REPO/archive/$ODOO_COMMIT.tar.gz"

  mkdir ./odoo_tmp
  puts-line "Fetching $ODOO_REPO (${ODOO_BRANCH}) @ (${ODOO_COMMIT})"
  curl -sL $ODOO_ARCHIVE 2> /dev/null | tar xz -C ./odoo_tmp --strip 1

  puts-line "python version"
  python --version
  
  #python -m ensurepip --upgrade

  puts-line "PIP version"
  python -m pip --version


  puts-line "Running Odoo setup.py"

  pip install --upgrade --no-dependencies --src=./.heroku/src --disable-pip-version-check --no-cache-dir ./odoo_tmp 2>&1 | tee $WARNINGS_LOG | cleanup-pip-output | indent
  
  # puts-line "DEBUG THIS"
  # pwd
  # ls -la
  # puts-line "CHECK IF EXIST: ./odoo_tmp/addons"
  # cd ./odoo_tmp/addons
  # pwd
  # ls -la
  # cd /
  # pwd
  # ls -la
  # cd app
  # pwd
  # ls -la
  # puts-line "CHECK IF EXIST:  .heroku/odoo/addons"
  # cd .heroku
  # pwd
  # ls -la
  # cd odoo
  # pwd
  # ls -la
  # cd addons
  # pwd ls -ls
  # puts-line "END DEBUG THIS"
  rm -rf .heroku/odoo/addons &> /dev/null || true
  mv ./odoo_tmp/addons /app/.heroku/odoo/addons

  # Keep stack
  echo $STACK > .heroku/odoo/stack.json

  if [ ! -f "./odoo_requirements.txt" ]; then
    cp ./odoo_tmp/requirements.txt ./odoo_requirements.txt
  else
    puts-line "Detected custom odoo_requirements.txt"
  fi

  # Cleanup
  rm -rf ./odoo_tmp
else
  puts-line "Odoo installation is up to date"
fi

# Export additional requirements
export REQUIREMENTS="$REQUIREMENTS odoo_requirements.txt"

# Export addon locations
export ODOOKU_ADDONS="$HOME/.heroku/odoo/lib/python2.7/site-packages/odoo/addons,$HOME/.heroku/odoo/addons"
if [ -d "./addons" ]; then
  puts-line "Detected addons directory"
  # add custom module paths here
  export ODOOKU_ADDONS="$ODOOKU_ADDONS,$HOME/addons,$HOME/addons/vittal_odoo_modules"
fi
